### ISSUE TITLE
Not working before page refresh

### ISSUE THREAD

**Issue by brenomzy** [JaeYeopHan/gatsby-remark-images-medium-zoom#12]
Hello,
if I access my case studies (markdown) via the page generator by slug, the plugin won't work initially, I need to manually refresh the markdown page for it to work properly, any ideas?

Thanks in advance.

**Comment by jbee37142** [comment]
@brenomzy hi, the performance observer polyfill will be added in a next release. I think it's good to check again

**Comment by brenomzy** [comment]
Alright, no problem!
Thank you!

**Comment by jbee37142** [comment]
@brenomzy  Could you check this commit? https://github.com/JaeYeopHan/gatsby-remark-images-medium-zoom/commit/1c1d1f7e205490bbaea60286266b38fe273708b6

maybe this issue was resolved with 1.7.0 version
