### ISSUE TITLE
Question: It works for external images markdown?

### ISSUE THREAD

**Issue by dantehemerson** [JaeYeopHan/gatsby-remark-images-medium-zoom#4]
I add an external image in my markdown.

```
Hi there,...

![Imgur](https://i.imgur.com/OIYtwiB.png)
```

But the plugin doesn't working. 

The repo for reproduction is:
https://github.com/dantehemerson/dantecalderon.dev/tree/f53bc510d3a154e296c0a175457bb0ae919e8d60

**Comment by jbee37142** [comment]
@dantehemerson Sorry for the late reply. i'll check it.

**Comment by jbee37142** [comment]
@dantehemerson 

![test](https://user-images.githubusercontent.com/17924127/66185467-7f909c80-e6ba-11e9-8461-836e2ecaa032.gif)

It seems to work nice! what's the problem?
Can you explain the supplement?

**Comment by BrunnerLivio** [comment]
Same issue here. I configured [gatsby-config.js](https://github.com/BrunnerLivio/brunnerliv.io/blob/a33325dc00c76debf3d4b1370b93c34704e1772d/gatsby-config.js#L21-L30) as specified in the readme. 
The markdown looks like this:

```md
![Download SVG image from flaticon](https://thepracticaldev.s3.amazonaws.com/i/dakpe45wkavx1spjcuzv.png)
```

It will get transpiled to this
```html
<img src="https://thepracticaldev.s3.amazonaws.com/i/dakpe45wkavx1spjcuzv.png" alt="Download SVG image from flaticon">
```
[Live demo](https://www.brunnerliv.io/articles/icon-web-font).

**Comment by emindeniz99** [comment]
Did you find a solution?

**Comment by dantehemerson** [comment]
Fixed, @BrunnerLivio @emindeniz99 You can add a CSS selector like this to include images:
```
 {
   resolve: `gatsby-remark-images-medium-zoom`,
   options: {
     includedSelector: '#post_body img',
   },
},
```
